# Generated by Django 4.1.7 on 2023-03-15 10:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('adresse', models.CharField(max_length=40, null=True)),
                ('telephone', models.CharField(max_length=15, null=True)),
                ('email', models.CharField(max_length=60, null=True)),
                ('pays', models.CharField(max_length=60, null=True)),
                ('ville', models.CharField(max_length=60, null=True)),
                ('longitude', models.FloatField(max_length=40, null=True)),
                ('latitude', models.FloatField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('designation', models.CharField(max_length=40, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_stock', models.IntegerField(null=True)),
                ('unite', models.CharField(max_length=60, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('date_modif', models.DateTimeField(auto_now=True)),
                ('pharmacie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.pharmacie')),
                ('produit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.produit')),
            ],
        ),
    ]
