# Generated by Django 4.1.7 on 2023-03-16 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0002_rename_pharmacie_pharmacieandaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaysVille',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pays', models.CharField(max_length=40, null=True)),
                ('ville', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Unite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeUnite', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='pharmacieandaccount',
            name='email',
        ),
        migrations.RemoveField(
            model_name='pharmacieandaccount',
            name='pays',
        ),
    ]
