# Generated by Django 4.1.7 on 2023-04-05 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0004_rename_pharmacieandaccount_pharmacie'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=40, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TourGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debut_tour', models.DateField(blank=True, null=True)),
                ('fin_tour', models.DateField(blank=True, null=True)),
                ('groupe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.groupe')),
            ],
        ),
        migrations.AddField(
            model_name='pharmacie',
            name='groupe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pharma.groupe'),
        ),
    ]
