# Generated by Django 4.1.7 on 2023-04-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0005_groupe_tourgarde_pharmacie_groupe'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacieGarde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie', models.CharField(max_length=40, null=True)),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=40, null=True)),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=40, null=True)),
            ],
        ),
    ]
