# Generated by Django 4.1.7 on 2023-04-26 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0006_pharmaciegarde'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaciegarde',
            name='latitude',
            field=models.DecimalField(decimal_places=30, max_digits=40, null=True),
        ),
        migrations.AlterField(
            model_name='pharmaciegarde',
            name='longitude',
            field=models.DecimalField(decimal_places=30, max_digits=40, null=True),
        ),
    ]
