# Generated by Django 4.1.7 on 2023-04-26 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0008_alter_pharmaciegarde_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaciegarde',
            name='latitude',
            field=models.FloatField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pharmaciegarde',
            name='longitude',
            field=models.FloatField(max_length=40, null=True),
        ),
    ]
