# Generated by Django 4.1.7 on 2023-05-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0010_remove_pharmacie_groupe_pharmaciegarde_groupe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmaciegarde',
            name='latitude',
            field=models.FloatField(default=0, max_length=40),
        ),
        migrations.AlterField(
            model_name='pharmaciegarde',
            name='longitude',
            field=models.FloatField(default=0, max_length=40),
        ),
    ]
