# Generated by Django 4.1.7 on 2023-05-05 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0011_alter_pharmaciegarde_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourgarde',
            name='debut_tour',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tourgarde',
            name='fin_tour',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
