# Generated by Django 4.1.7 on 2023-05-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0012_alter_tourgarde_debut_tour_alter_tourgarde_fin_tour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourgarde',
            name='debut_tour',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tourgarde',
            name='fin_tour',
            field=models.DateField(null=True),
        ),
    ]
