# Generated by Django 4.1.7 on 2023-06-13 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0018_alter_stock_pharmacie_alter_stock_quantite_stock_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdreVente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pharmacie_ordre', models.CharField(max_length=40, null=True)),
                ('produit_ordre', models.CharField(max_length=60, null=True)),
                ('qte_produit', models.IntegerField(default=0, null=True)),
                ('unite_ordre', models.CharField(max_length=40, null=True)),
                ('valider', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
