# Generated by Django 4.1.7 on 2023-06-13 15:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0019_ordrevente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordrevente',
            name='date_ajout',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
